### ISSUE TITLE
Xcode library check for reminders-cli

### ISSUE THREAD

**Issue by a-b** [keith/homebrew-formulae#2]
Please consider adding dependency check to the
https://github.com/keith/homebrew-formulae/blob/master/Formula/reminders-cli.rb

```
dyld: Library not loaded: @rpath/libswiftAppKit.dylib
  Referenced from: /usr/local/bin/reminders
  Reason: image not found
```

**Comment by keith** [comment]
Please build now that https://github.com/keith/homebrew-formulae/pull/3 is merged. Let me know if this doesn't work!

**Comment by keith** [comment]
Oh hey man! haha
