### ISSUE TITLE
sha1 deprecation warning for the taps

### ISSUE THREAD

**Issue by junkblocker** [keith/homebrew-formulae#4]
This morning

```
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/keith/homebrew-formulae/Formula/zap.rb:4:in `<class:Zap>'
Please report this to the keith/formulae tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/keith/homebrew-formulae/Formula/zap.rb:4:in `<class:Zap>'
Please report this to the keith/formulae tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/keith/homebrew-formulae/Formula/zap.rb:4:in `<class:Zap>'
Please report this to the keith/formulae tap!
```

**Comment by keith** [comment]
Ah yes thanks. I'll bump these.

**Comment by chris-araman** [comment]
Also seeing these for `xcpretty.rb:4` and `cocoapods.rb:6`.

**Comment by szymonh** [comment]
I've observed the following:

> Warning: Calling Resource#sha1 is deprecated!
> Use Resource#sha256 instead.
> /opt/boxen/homebrew/Library/Taps/boxen/homebrew-brews/dnsmasq.rb:6:in `<class:Dnsmasq>'
> Please report this to the boxen/brews tap!

> Warning: Calling Formula.sha1 is deprecated!
> Use Formula.sha256 instead.
> /opt/boxen/homebrew/Library/Taps/boxen/homebrew-brews/nginx.rb:6:in `<class:Nginx>'
> Please report this to the boxen/brews tap!

**Comment by keith** [comment]
Closed by https://github.com/keith/homebrew-formulae/pull/5

Thanks everyone!

**Comment by chris-araman** [comment]
I'm not sure why, but I still saw these warnings after `brew update`. I was able to workaround the issue using:

```
brew untap keith/homebrew-formulae
brew tap keith/homebrew-formulae
brew doctor
```

@keith, do we need some other change for `brew update` to automatically pick up these hashes?

**Comment by keith** [comment]
Interesting, when I do this I no longer see these errors.

Could you be hit with this problem
https://twitter.com/MacHomebrew/status/763686348041641984 ?

## 

Keith Smiley

**Comment by chris-araman** [comment]
Sounds likely. Thanks.
